//! Private shell integration used only by JunQi's embedded terminal.
//!
//! Kooky tracks the current directory through OSC 7. Merely parsing that
//! sequence in the renderer is not enough: stock zsh/bash/fish sessions do not
//! consistently emit it. These tiny, application-owned wrappers replay the
//! user's shell configuration and then emit OSC 7 without editing any user rc
//! file. If preparing a wrapper fails, callers receive a normal login shell.

use std::ffi::OsStr;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::{Mutex, OnceLock};

use portable_pty::CommandBuilder;
use tauri::{AppHandle, Manager};

const INTEGRATION_DIR: &str = "terminal-shell";

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum ShellKind {
    Zsh,
    Bash,
    Fish,
    Other,
}

fn integration_lock() -> &'static Mutex<()> {
    static LOCK: OnceLock<Mutex<()>> = OnceLock::new();
    LOCK.get_or_init(|| Mutex::new(()))
}

fn detect_shell_kind(program: &str) -> ShellKind {
    match Path::new(program)
        .file_name()
        .and_then(OsStr::to_str)
        .unwrap_or(program)
        .trim_end_matches(".exe")
        .to_ascii_lowercase()
        .as_str()
    {
        "zsh" => ShellKind::Zsh,
        "bash" => ShellKind::Bash,
        "fish" => ShellKind::Fish,
        _ => ShellKind::Other,
    }
}

fn login_env_value(name: &str) -> Option<String> {
    crate::platform::login_shell_env()
        .iter()
        .find(|(key, _)| key == name)
        .map(|(_, value)| value.clone())
        .filter(|value| !value.is_empty())
}

fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

fn integration_root(app: &AppHandle) -> Result<PathBuf, String> {
    app.path()
        .app_data_dir()
        .map(|path| path.join(INTEGRATION_DIR))
        .map_err(|error| format!("resolve terminal integration directory: {error}"))
}

fn write_if_changed(path: &Path, contents: &str, executable: bool) -> Result<(), String> {
    let current = fs::read_to_string(path).ok();
    if current.as_deref() != Some(contents) {
        let parent = path.parent().ok_or("invalid terminal integration path")?;
        fs::create_dir_all(parent).map_err(|error| error.to_string())?;
        let temporary = parent.join(format!(
            ".{}.{}.tmp",
            path.file_name().and_then(OsStr::to_str).unwrap_or("shell"),
            std::process::id()
        ));
        fs::write(&temporary, contents).map_err(|error| error.to_string())?;
        fs::rename(&temporary, path).map_err(|error| error.to_string())?;
    }

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mode = if executable { 0o700 } else { 0o600 };
        fs::set_permissions(path, fs::Permissions::from_mode(mode))
            .map_err(|error| error.to_string())?;
    }
    let _ = executable;
    Ok(())
}

fn zsh_wrapper() -> &'static str {
    r#"# JunQi private zsh integration. This file is generated by the app.
if [[ -n "${JUNQI_ORIGINAL_ZDOTDIR:-}" ]]; then
  export ZDOTDIR="$JUNQI_ORIGINAL_ZDOTDIR"
  unset JUNQI_ORIGINAL_ZDOTDIR
else
  unset ZDOTDIR
fi

# Replay the user chain after restoring their real ZDOTDIR. This wrapper is
# only the initial lookup target; it does not replace user configuration.
[[ -r "${ZDOTDIR:-$HOME}/.zshenv" ]] && source "${ZDOTDIR:-$HOME}/.zshenv"
[[ -r "${ZDOTDIR:-$HOME}/.zprofile" ]] && source "${ZDOTDIR:-$HOME}/.zprofile"
[[ -r "${ZDOTDIR:-$HOME}/.zshrc" ]] && source "${ZDOTDIR:-$HOME}/.zshrc"

autoload -Uz add-zsh-hook
_junqi_osc7_pwd() { local _s=$?; printf '\e]7;file://%s%s\e\\' "${HOST:-localhost}" "$PWD"; return $_s }
add-zsh-hook chpwd _junqi_osc7_pwd
_junqi_osc7_pwd
"#
}

fn bash_rc() -> &'static str {
    r#"# JunQi private bash integration. This file is generated by the app.
# Interactive non-login bash does not read a profile. Replay the same first
# login rc Bash would select; if none exists, load .bashrc once.
_junqi_login_rc_loaded=
for _junqi_rc in "$HOME/.bash_profile" "$HOME/.bash_login" "$HOME/.profile"; do
  if [[ -r "$_junqi_rc" ]]; then
    source "$_junqi_rc"
    _junqi_login_rc_loaded=1
    break
  fi
done
unset _junqi_rc
if [[ -z "$_junqi_login_rc_loaded" && -r "$HOME/.bashrc" ]]; then
  source "$HOME/.bashrc"
fi
unset _junqi_login_rc_loaded

_junqi_osc7_pwd() { printf '\e]7;file://%s%s\e\\' "${HOSTNAME:-localhost}" "$PWD"; }
PROMPT_COMMAND="_junqi_osc7_pwd${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
_junqi_osc7_pwd
"#
}

fn fish_vendor_config() -> &'static str {
    r#"# JunQi private fish integration. This file is generated by the app.
set -l __junqi_host (hostname)
function __junqi_emit_osc7 --on-event fish_prompt
  printf '\e]7;file://%s%s\e\\' "$__junqi_host" "$PWD"
end
__junqi_emit_osc7
"#
}

fn default_shell_command(cwd: &Path) -> CommandBuilder {
    let shell = crate::platform::default_shell_command();
    let mut command = CommandBuilder::new(&shell.program);
    for argument in &shell.args {
        command.arg(argument);
    }
    command.cwd(cwd);
    command
}

fn apply_terminal_environment(command: &mut CommandBuilder) {
    let login_env = crate::platform::login_shell_env();
    for (key, value) in login_env {
        command.env(key, value);
    }
    let has_login_var = |name: &str| login_env.iter().any(|(key, _)| key == name);
    if !has_login_var("LANG") {
        command.env("LANG", "en_US.UTF-8");
    }
    if !has_login_var("LC_CTYPE") {
        command.env("LC_CTYPE", "en_US.UTF-8");
    }
    command.env("TERM", "xterm-256color");
    command.env("COLORTERM", "truecolor");
}

/// Build a login-equivalent shell command with best-effort private integration.
/// Any filesystem failure falls back to the plain shell rather than preventing
/// a user from opening a terminal.
pub fn build_interactive_shell_command(app: &AppHandle, cwd: &Path) -> CommandBuilder {
    let shell = crate::platform::default_shell_command();

    #[cfg(not(unix))]
    {
        let mut command = default_shell_command(cwd);
        apply_terminal_environment(&mut command);
        return command;
    }

    #[cfg(unix)]
    {
        let mut command = match prepare_unix_integration(app, cwd, &shell.program) {
            Ok(Some(command)) => command,
            Ok(None) | Err(_) => default_shell_command(cwd),
        };
        apply_terminal_environment(&mut command);

        // ZDOTDIR and XDG_DATA_DIRS must be set after the login environment,
        // otherwise setup would overwrite this session-only integration.
        if detect_shell_kind(&shell.program) == ShellKind::Zsh {
            if let Ok(root) = prepare_zsh_integration(app) {
                if let Some(original) = login_env_value("ZDOTDIR") {
                    command.env("JUNQI_ORIGINAL_ZDOTDIR", original);
                } else {
                    command.env_remove("JUNQI_ORIGINAL_ZDOTDIR");
                }
                command.env("ZDOTDIR", root);
            }
        }
        if detect_shell_kind(&shell.program) == ShellKind::Fish {
            if let Ok(root) = prepare_fish_integration(app) {
                let existing = login_env_value("XDG_DATA_DIRS")
                    .unwrap_or_else(|| "/usr/local/share:/usr/share".to_string());
                command.env(
                    "XDG_DATA_DIRS",
                    format!("{}:{}", root.to_string_lossy(), existing),
                );
            }
        }
        command
    }
}

#[cfg(unix)]
fn prepare_unix_integration(
    app: &AppHandle,
    cwd: &Path,
    shell_program: &str,
) -> Result<Option<CommandBuilder>, String> {
    if detect_shell_kind(shell_program) != ShellKind::Bash {
        return Ok(None);
    }
    let launcher = prepare_bash_integration(app, shell_program)?;
    let mut command = CommandBuilder::new(launcher);
    command.cwd(cwd);
    Ok(Some(command))
}

#[cfg(unix)]
fn prepare_zsh_integration(app: &AppHandle) -> Result<PathBuf, String> {
    let _guard = integration_lock()
        .lock()
        .map_err(|_| "terminal integration lock poisoned".to_string())?;
    let root = integration_root(app)?.join("zsh");
    fs::create_dir_all(&root).map_err(|error| error.to_string())?;
    write_if_changed(&root.join(".zshrc"), zsh_wrapper(), false)?;
    Ok(root)
}

#[cfg(unix)]
fn prepare_bash_integration(app: &AppHandle, bash_program: &str) -> Result<PathBuf, String> {
    let _guard = integration_lock()
        .lock()
        .map_err(|_| "terminal integration lock poisoned".to_string())?;
    let root = integration_root(app)?.join("bash");
    fs::create_dir_all(&root).map_err(|error| error.to_string())?;
    let rc_path = root.join("junqi-bashrc");
    let launcher_path = root.join("junqi-bash-launch");
    write_if_changed(&rc_path, bash_rc(), false)?;
    let launcher = format!(
        "#!/bin/sh\nexec {} --rcfile {} -i\n",
        shell_quote(bash_program),
        shell_quote(&rc_path.to_string_lossy()),
    );
    write_if_changed(&launcher_path, &launcher, true)?;
    Ok(launcher_path)
}

#[cfg(unix)]
fn prepare_fish_integration(app: &AppHandle) -> Result<PathBuf, String> {
    let _guard = integration_lock()
        .lock()
        .map_err(|_| "terminal integration lock poisoned".to_string())?;
    let root = integration_root(app)?.join("fish-data");
    let config_path = root.join("fish").join("vendor_conf.d").join("junqi.fish");
    write_if_changed(&config_path, fish_vendor_config(), false)?;
    Ok(root)
}

#[cfg(test)]
mod tests {
    use super::{
        bash_rc, detect_shell_kind, fish_vendor_config, shell_quote, zsh_wrapper, ShellKind,
    };

    #[test]
    fn detects_supported_shells_by_program_basename() {
        assert_eq!(detect_shell_kind("/bin/zsh"), ShellKind::Zsh);
        assert_eq!(detect_shell_kind("bash"), ShellKind::Bash);
        assert_eq!(detect_shell_kind("/opt/homebrew/bin/fish"), ShellKind::Fish);
        assert_eq!(detect_shell_kind("/bin/sh"), ShellKind::Other);
    }

    #[test]
    fn wrappers_replay_user_config_and_emit_osc7_without_writing_user_rc_files() {
        assert!(zsh_wrapper().contains("${ZDOTDIR:-$HOME}/.zshrc"));
        assert!(zsh_wrapper().contains("add-zsh-hook chpwd _junqi_osc7_pwd"));
        assert!(bash_rc().contains("$HOME/.bash_profile"));
        assert!(bash_rc().contains("PROMPT_COMMAND"));
        assert!(fish_vendor_config().contains("--on-event fish_prompt"));
    }

    #[test]
    fn shell_quote_preserves_single_quotes() {
        assert_eq!(shell_quote("/tmp/a b"), "'/tmp/a b'");
        assert_eq!(shell_quote("it's"), "'it'\\''s'");
    }
}
