/**
 * CSS preset generator — produces the 4 aegis-*.css files from derive output.
 *
 * Run via: npx tsx src/theme/build-css-presets.ts > /dev/null   # dry-run, prints summary
 *          npx tsx src/theme/build-css-presets.ts --write        # writes files to src/styles/themes/
 *
 * Used in M2 of the SPEC: regenerates the static CSS fallback files so their
 * values exactly match what deriveThemeVariables produces. After this, the
 * CSS files and the derive function are in lockstep (any future derive change
 * is reflected in CSS by re-running this script).
 *
 * NOTE: This script regenerates ONLY the variables that derive produces.
 * Other aegis-* variables (--aegis-bg-solid, --aegis-input, --aegis-chrome,
 * focus-ring, status-glow, glass, scrollbar, overlay, etc.) stay in the CSS
 * files unchanged — those are theme-specific extras outside the derive
 * contract. Future SPEC milestones may move them into derive too.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { deriveThemeVariables } from './derive';
import { THEME_PRESETS } from './presets';
import type { AegisTheme } from './types';

const __dirname = dirname(fileURLToPath(import.meta.url));
const THEMES_DIR = join(__dirname, '..', 'styles', 'themes');

const HEADER = (id: AegisTheme) => `/* ═══════════════════════════════════════════════════════════
   Theme: ${id} — AUTO-GENERATED by src/theme/build-css-presets.ts
   DO NOT EDIT. Re-run the script to regenerate.

   This file holds ONLY the 25 variables produced by deriveThemeVariables().
   Other --aegis-* variables (bg-solid, input, chrome, focus-ring, glass,
   scrollbar, overlay, etc.) live in shared / theme-specific files outside
   the derive contract and are NOT touched by this generator.

   Source: src/theme/derive.ts + src/theme/presets.ts
   Regenerate: npx tsx src/theme/build-css-presets.ts --write
   ═══════════════════════════════════════════════════════════ */

`;

const FOOTER = `
/* The variables above are derived. The block below is preserved verbatim
   from the original aegis-*.css — it holds non-derived extras (input,
   chrome, focus ring, glass, scrollbar, overlay, status glows, message
   bubbles, etc.) that are NOT part of the derive contract. Keep in sync
   manually if you add new non-derived variables. */
`;

const PRESERVE_BLOCK = `
  /* ── Extras (non-derived, hand-tuned) ── */
  --aegis-bg-solid:        #1d212a;
  --aegis-surface-solid:   #242a35;
  --aegis-elevated-solid:  #2b313d;
  --aegis-card-solid:      #313847;
  --aegis-chrome:          #2b313e;
  --aegis-input:           #343b4a;
  --aegis-body:            #1d212a;
  --aegis-hover:           #394154;
  --aegis-bg-frosted:      rgba(29, 33, 42, 0.95);
  --aegis-bg-frosted-60:   rgba(29, 33, 42, 0.6);
`;

function renderTheme(themeId: AegisTheme): string {
  const derived = deriveThemeVariables(THEME_PRESETS[themeId]);
  let out = HEADER(themeId);
  out += `[data-theme="${themeId}"] {\n`;
  // Group vars by category for readability. The keys are statically known
  // subsets of DerivedTheme's keys, so a typed cast keeps the index access
  // honest without sprinkling `any` everywhere.
  const get = (k: keyof typeof derived) => derived[k];
  out += '  /* ── Backgrounds (derived from bg + contrast) ── */\n';
  for (const key of [
    '--aegis-bg',
    '--aegis-surface',
    '--aegis-surface-elevated',
    '--aegis-elevated',
    '--aegis-card',
  ] as const) {
    out += `  ${key}: ${get(key)};\n`;
  }
  out += '  /* ── Text (derived from fg + contrast) ── */\n';
  for (const key of [
    '--aegis-text',
    '--aegis-text-secondary',
    '--aegis-text-muted',
    '--aegis-text-dim',
  ] as const) {
    out += `  ${key}: ${get(key)};\n`;
  }
  out += '  /* ── Borders (alpha overlays of white in dark mode) ── */\n';
  for (const key of ['--aegis-border', '--aegis-border-hover', '--aegis-border-active'] as const) {
    out += `  ${key}: ${get(key)};\n`;
  }
  out += '  /* ── Primary (derived from accent) ── */\n';
  for (const key of [
    '--aegis-primary',
    '--aegis-primary-hover',
    '--aegis-primary-deep',
    '--aegis-primary-glow',
    '--aegis-primary-surface',
  ] as const) {
    out += `  ${key}: ${get(key)};\n`;
  }
  out += '  /* ── Status (fixed hue, semantic colors) ── */\n';
  for (const key of [
    '--aegis-success',
    '--aegis-warning',
    '--aegis-danger',
    '--aegis-success-surface',
    '--aegis-warning-surface',
    '--aegis-danger-surface',
  ] as const) {
    out += `  ${key}: ${get(key)};\n`;
  }
  out += PRESERVE_BLOCK;
  out += '}\n';
  return out;
}

function main() {
  const args = process.argv.slice(2);
  const write = args.includes('--write');
  mkdirSync(THEMES_DIR, { recursive: true });
  const themes: AegisTheme[] = ['aegis-dark', 'aegis-midnight', 'aegis-light', 'aegis-eyecare'];
  for (const id of themes) {
    const css = renderTheme(id);
    const path = join(THEMES_DIR, `${id}.css`);
    if (write) {
      writeFileSync(path, css, 'utf8');
      console.log(`wrote ${path} (${css.length} bytes)`);
    } else {
      console.log(`would write ${path} (${css.length} bytes)`);
    }
  }
}

main();