export type SetupStep =
  | 'welcome'
  | 'detecting'
  | 'environment-review'
  | 'storage'
  | 'gateway-stopped'
  | 'choosing-mode'
  | 'checking'
  | 'install-git'
  | 'git-missing'
  | 'node-missing'
  | 'install-node'
  | 'install-openclaw'
  | 'gateway-ready'
  | 'update-openclaw'
  | 'configure-openclaw'
  | 'ready'
  | 'error';
