import type React from "react";

export const font = {
  fontPanel: {
    flex: 1,
    overflowY: "auto" as const,
    display: "flex",
    flexDirection: "column" as const,
    gap: 18,
    padding: 20,
  },
  fontSection: {
    padding: "16px 18px",
    borderRadius: 8,
    border: "1px solid var(--aegis-border)",
    background: "var(--aegis-elevated)",
  },
  fontPreviewSection: {
    padding: "14px 18px",
    borderRadius: 8,
    border: "1px solid var(--aegis-border)",
    background: "var(--aegis-elevated)",
    display: "flex",
    flexDirection: "column" as const,
    gap: 8,
  },
  fontPreviewLabel: {
    fontSize: 12,
    fontWeight: 600,
    color: "rgb(var(--aegis-text-secondary))",
  },
  fontPreviewInner: {
    padding: "10px 12px",
    borderRadius: 6,
    border: "1px solid var(--aegis-border)",
    background: "var(--aegis-card)",
    display: "flex",
    flexDirection: "column" as const,
    gap: 6,
  },
  fontInlinePreview: {
    marginTop: 4,
    padding: "10px 12px",
    borderRadius: 6,
    border: "1px solid var(--aegis-border)",
    background: "var(--aegis-card)",
    display: "flex",
    flexDirection: "column" as const,
    gap: 6,
  },
  fontPreviewHeaderRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  fontPreviewMeta: {
    fontSize: 11,
    color: "rgb(var(--aegis-text-dim))",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  fontPreviewText: {
    fontSize: 13,
    color: "rgb(var(--aegis-text))",
    lineHeight: 1.5,
  },
  fontPreviewCode: {
    color: "rgb(var(--aegis-text-secondary))",
    lineHeight: 1.5,
  },
  fontPreviewDivider: {
    height: 1,
    background: "var(--aegis-border)",
    margin: "2px 0",
  },
  fontCodePreviewWindow: {
    margin: 0,
    padding: "10px 0",
    borderRadius: 6,
    border: "1px solid rgba(255, 255, 255, 0.09)",
    background: "linear-gradient(180deg, #171b24, #10141d)",
    color: "#d6deeb",
    boxShadow: "var(--shadow-sm)",
    overflowX: "auto" as const,
    lineHeight: 1.55,
  },
  fontCodeLine: {
    display: "flex",
    minWidth: "max-content",
  },
  fontCodeLineNo: {
    width: 34,
    paddingRight: 10,
    color: "rgba(214, 222, 235, 0.36)",
    textAlign: "right" as const,
    userSelect: "none" as const,
    flexShrink: 0,
    fontVariantNumeric: "tabular-nums" as const,
  },
  fontCodeText: {
    paddingRight: 14,
    whiteSpace: "pre" as const,
  },
  fontCodeKeyword: {
    color: "#c792ea",
    fontWeight: 650,
  },
  fontCodeString: {
    color: "#ecc48d",
  },
  fontCodeNumber: {
    color: "#f78c6c",
  },
  fontCodeComment: {
    color: "#7f8da3",
    fontStyle: "italic",
  },
  fontSettingLabel: {
    fontSize: 13,
    fontWeight: 600,
    color: "rgb(var(--aegis-text))",
  },
  fontSettingHint: {
    fontSize: 11.5,
    color: "rgb(var(--aegis-text-dim))",
    lineHeight: 1.45,
  },
  fontSizeRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
  },
  fontSizeLabelCol: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 3,
    minWidth: 0,
  },
  fontSizeControls: {
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    color: "rgb(var(--aegis-text-secondary))",
    fontFamily: "var(--font-mono)",
    fontSize: 12,
  },
  fontSizeInput: {
    width: 54,
    height: 28,
    padding: "0 6px",
    borderRadius: 6,
    border: "1px solid var(--aegis-border)",
    background: "var(--aegis-card)",
    color: "rgb(var(--aegis-text-secondary))",
    fontSize: 12,
    fontWeight: 600,
    fontFamily: "var(--font-mono)",
    textAlign: "center" as const,
    outline: "none",
  },
  fontSizeUnit: {
    color: "rgb(var(--aegis-text-dim))",
  },
  fontSelectorInner: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 6,
  },
  fontSelectorLabelSection: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 3,
  },
  fontSelectorLabelRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  fontSelectorResetBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    background: "none",
    border: "none",
    color: "rgb(var(--aegis-text-dim))",
    fontSize: 11,
    cursor: "pointer",
    padding: "2px 6px",
    borderRadius: 4,
  },
  fontSelectorTrigger: {
    width: "100%",
  },
  fontSelectorTriggerContent: {
    flex: 1,
    textAlign: "left" as const,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  fontSaveBtn: {
    padding: "8px 20px",
    borderRadius: 6,
    border: "none",
    background: "rgb(var(--aegis-primary))",
    color: "var(--aegis-btn-primary-text)",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    alignSelf: "flex-end" as const,
  },
} satisfies Record<string, React.CSSProperties>;
