import type React from "react";

export const layout = {
  root: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    background: "var(--aegis-bg)",
    overflow: "hidden",
  },
  welcomeBody: {
    height: "100%",
    display: "flex",
    overflow: "hidden",
    background: "var(--aegis-bg)",
  },
  welcomeMain: { flex: 1, display: "flex", overflow: "hidden" },
  sidebar: {
    width: 220,
    flexShrink: 0,
    background: "linear-gradient(180deg, var(--aegis-surface), var(--aegis-surface-elevated))",
    borderRight: "1px solid var(--aegis-border)",
    display: "flex",
    flexDirection: "column",
    padding: "18px 14px 14px",
  },
  sidebarBrand: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "2px 6px 18px",
    marginBottom: 14,
    borderBottom: "1px solid var(--aegis-border)",
  },
  sidebarBrandIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    background: "var(--brand-mark-gradient)",
    padding: 4,
    boxShadow: "0 10px 20px var(--brand-mark-glow)",
  },
  sidebarBrandBadge: {
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    width: "100%",
    height: "100%",
    borderRadius: 9,
    background: "var(--brand-mark-inner-bg)",
    color: "var(--brand-mark-fg)",
    fontSize: 15,
    fontWeight: 800,
    letterSpacing: 0.6,
    paddingBottom: 4,
  },
  sidebarBrandTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: "rgb(var(--aegis-text))",
    lineHeight: 1.2,
  },
  sidebarBrandMeta: { marginTop: 3, fontSize: 12, color: "rgb(var(--aegis-text-muted))" },
  sidebarNav: { display: "flex", flexDirection: "column", gap: 6 },
  sidebarSectionTitle: {
    fontSize: 11,
    fontWeight: 700,
    color: "rgb(var(--aegis-text-dim))",
    letterSpacing: 0.7,
    padding: "0 10px 6px",
    textTransform: "uppercase" as const,
  },
  sidebarItem: {
    display: "flex",
    alignItems: "center",
    padding: "11px 12px",
    borderRadius: 10,
    cursor: "pointer",
    fontWeight: 500,
    transition: "background 0.18s ease, color 0.18s ease",
    border: "1px solid transparent",
  },
  sidebarItemMeta: {
    marginLeft: "auto",
    minWidth: 22,
    height: 22,
    padding: "0 7px",
    borderRadius: 999,
    background: "var(--badge-muted-bg)",
    color: "rgb(var(--aegis-text-muted))",
    fontSize: 11,
    fontWeight: 700,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  sidebarFooter: {
    marginTop: "auto",
    paddingTop: 10,
    borderTop: "1px solid var(--aegis-border)",
    display: "flex",
    justifyContent: "flex-start",
  },
  sidebarFooterActions: { display: "flex", alignItems: "center", gap: 4 },
  sidebarIconBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 4,
    borderRadius: 6,
    display: "flex",
    alignItems: "center",
    position: "relative",
    overflow: "visible",
    opacity: 0.5,
  },
  welcomePane: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    background: "var(--aegis-elevated)",
  },
  searchRow: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "18px 22px 12px",
    borderBottom: "1px solid var(--aegis-border)",
    background: "var(--aegis-elevated)",
    flexShrink: 0,
  },
  searchBox: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    gap: 12,
    minWidth: 0,
    padding: "12px 16px",
    background: "var(--aegis-input)",
    border: "1px solid var(--aegis-border)",
    borderRadius: 12,
    transition: "box-shadow 0.18s ease, border-color 0.18s ease",
  },
  searchInput: {
    flex: 1,
    border: "none",
    outline: "none",
    background: "transparent",
    color: "rgb(var(--aegis-text))",
    fontSize: 15,
    fontWeight: 500,
  },
  actionRow: { display: "flex", alignItems: "center", gap: 10, flexShrink: 0 },
  primaryActionBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    height: 38,
    padding: "0 16px",
    background: "var(--aegis-card)",
    color: "rgb(var(--aegis-text))",
    border: "1px solid var(--aegis-border)",
    borderRadius: 10,
    fontSize: 13.5,
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "var(--shadow-xs)",
  },
  projectSectionHeader: { padding: "14px 22px 6px", flexShrink: 0 },
  projectSectionTitle: { fontSize: 14, fontWeight: 700, color: "rgb(var(--aegis-text))" },
  projectSectionCaption: { marginTop: 4, fontSize: 12, color: "rgb(var(--aegis-text-muted))" },
  projectList: { flex: 1, overflowY: "auto", padding: "4px 22px 18px" },
  projectItem: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    width: "100%",
    minHeight: 72,
    padding: "12px 14px",
    border: "1px solid transparent",
    borderRadius: 14,
    cursor: "pointer",
    textAlign: "left",
    fontFamily: "var(--font-ui)",
    transition: "background 0.16s ease, border-color 0.16s ease",
  },
  projectName: {
    fontSize: 14,
    fontWeight: 650,
    color: "rgb(var(--aegis-text))",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  projectMeta: {
    marginTop: 4,
    fontSize: 11.5,
    color: "rgb(var(--aegis-text-muted))",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  branchBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    fontSize: 10.5,
    color: "rgb(var(--aegis-text-secondary))",
    background: "var(--aegis-elevated)",
    border: "1px solid var(--aegis-border)",
    padding: "4px 8px",
    borderRadius: 999,
    flexShrink: 0,
  },
  projectTag: {
    fontSize: 10.5,
    fontWeight: 700,
    color: "rgb(var(--aegis-text-dim))",
    letterSpacing: 0.7,
    flexShrink: 0,
  },
  projectPinBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    marginLeft: 8,
    padding: "4px 8px",
    fontSize: 10.5,
    fontWeight: 600,
    borderRadius: 999,
    border: "1px solid transparent",
    cursor: "pointer",
    flexShrink: 0,
    whiteSpace: "nowrap",
    fontFamily: "var(--font-ui)",
    transition: "color 0.15s ease, border-color 0.15s ease, background 0.15s ease",
  },
  projectPinBtnPinned: {
    background: "var(--aegis-elevated)",
    borderColor: "var(--aegis-border)",
    color: "rgb(var(--aegis-text-secondary))",
  },
  projectPinBtnHidden: {
    background: "transparent",
    borderColor: "var(--aegis-border)",
    color: "rgb(var(--aegis-text-dim))",
  },
  railHiddenIcon: {
    marginLeft: "auto",
    flexShrink: 0,
  },
  emptyState: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    padding: 32,
    textAlign: "center",
  },
  emptyOpenBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    padding: "10px 18px",
    background: "var(--aegis-card)",
    color: "rgb(var(--aegis-text-secondary))",
    border: "1px solid var(--aegis-border)",
    borderRadius: 12,
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    boxShadow: "var(--shadow-sm)",
  },
  projectBody: { flex: 1, display: "flex", overflow: "hidden" },
  mainContent: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    background: "var(--aegis-elevated)",
  },
  placeholderView: { flex: 1, display: "flex", alignItems: "center", justifyContent: "center" },
} satisfies Record<string, React.CSSProperties>;
