import type React from "react";

const exportBtnBase = {
  display: "flex",
  alignItems: "center",
  gap: 5,
  padding: "4px 10px",
  background: "none",
  border: "1px solid rgb(var(--aegis-primary))",
  borderRadius: 5,
  fontSize: 12,
  color: "rgb(var(--aegis-primary))",
  flexShrink: 0,
} as const;

export const terminal = {
  runHeader: {
    padding: "16px 20px 8px",
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexShrink: 0,
  },
  runMetaRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 11,
    color: "rgb(var(--aegis-text-muted))",
    minWidth: 0,
    overflow: "hidden",
  },
  runMetaFixed: {
    flexShrink: 0,
  },
  runMetaBranchInline: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    minWidth: 0,
    overflow: "hidden",
  },
  runMetaBranchText: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  runMetricsRow: {
    marginTop: 8,
    display: "flex",
    gap: 12,
    flexWrap: "wrap" as const,
  },
  runMetricPill: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    padding: "3px 8px",
    borderRadius: 6,
    background: "var(--aegis-input)",
    border: "1px solid var(--aegis-border)",
  },
  runMetricPillButton: {
    font: "inherit",
    cursor: "pointer",
  },
  runMetricPillLabel: {
    fontSize: 10,
    color: "rgb(var(--aegis-text-dim))",
    fontWeight: 600,
    textTransform: "uppercase" as const,
    letterSpacing: 0.4,
  },
  runMetricPillValue: {
    fontSize: 11,
    color: "rgb(var(--aegis-text))",
    fontWeight: 600,
  },
  runSessionFilePillWrap: {
    position: "relative" as const,
    display: "inline-flex",
    alignItems: "center",
  },
  runSessionStatusDot: {
    display: "inline-block",
    position: "static" as const,
    bottom: "auto",
    right: "auto",
    flexShrink: 0,
  },
  runSessionCopyTooltip: {
    position: "absolute" as const,
    left: "50%",
    bottom: "calc(100% + 6px)",
    transform: "translateX(-50%)",
    zIndex: 20,
    padding: "5px 8px",
    borderRadius: 6,
    background: "var(--aegis-card)",
    border: "1px solid var(--aegis-border)",
    boxShadow: "0 8px 24px rgba(0, 0, 0, 0.18)",
    color: "rgb(var(--aegis-text-secondary))",
    fontSize: 11,
    fontWeight: 600,
    lineHeight: 1.4,
    whiteSpace: "nowrap" as const,
    pointerEvents: "none" as const,
  },
  cancelBtn: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    padding: "4px 10px",
    background: "none",
    border: "1px solid var(--aegis-border)",
    borderRadius: 5,
    fontSize: 12,
    color: "rgb(var(--aegis-text-muted))",
    cursor: "pointer",
    flexShrink: 0,
  },
  exportBtn: { ...exportBtnBase, cursor: "pointer" as const },
  exportBtnBusy: { ...exportBtnBase, cursor: "not-allowed" as const, opacity: 0.6 },
  resumeBtn: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    padding: "4px 10px",
    background: "none",
    border: "1px solid rgb(var(--aegis-primary))",
    borderRadius: 5,
    fontSize: 12,
    color: "rgb(var(--aegis-primary))",
    cursor: "pointer",
    flexShrink: 0,
  },
  doneBtn: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    padding: "4px 10px",
    background: "none",
    border: "1px solid rgba(46, 160, 67, 0.35)",
    borderRadius: 5,
    fontSize: 12,
    color: "var(--success)",
    cursor: "pointer",
    flexShrink: 0,
  },
  terminalContainer: { flex: 1, overflow: "hidden" as const, padding: "10px 0 10px 10px" },
  interruptedSessionWrap: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden",
    background: "var(--aegis-bg)",
  },
  interruptedBanner: {
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap" as const,
    gap: 7,
    minHeight: 38,
    padding: "4px 28px",
    borderBottom: "1px solid var(--aegis-border)",
    background: "var(--aegis-bg)",
  },
  interruptedBannerIcon: {
    width: 18,
    height: 18,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    color: "rgb(var(--aegis-warning))",
    flexShrink: 0,
  },
  interruptedBannerBody: {
    minWidth: 0,
    flex: "1 1 180px",
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    flexWrap: "wrap" as const,
  },
  interruptedBannerTitle: {
    fontSize: 12.5,
    fontWeight: 650,
    color: "rgb(var(--aegis-text))",
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  interruptedBannerText: {
    fontSize: 12,
    lineHeight: 1.5,
    color: "rgb(var(--aegis-text-muted))",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  interruptedBannerActions: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "flex-end",
    flexWrap: "wrap" as const,
    gap: 5,
    flexShrink: 0,
  },
  interruptedNoSessionPane: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "24px 32px",
    color: "rgb(var(--aegis-text-dim))",
    fontSize: 13,
    lineHeight: 1.6,
    textAlign: "center" as const,
  },
  interruptedPrimaryBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    padding: "3px 8px",
    borderRadius: 5,
    border: "1px solid var(--aegis-border)",
    color: "rgb(var(--aegis-text))",
    background: "var(--aegis-card)",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    minHeight: 26,
    whiteSpace: "nowrap" as const,
  },
  interruptedSecondaryBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    padding: "3px 8px",
    borderRadius: 5,
    border: "1px solid rgba(46, 160, 67, 0.24)",
    color: "var(--success)",
    background: "rgba(46, 160, 67, 0.055)",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    minHeight: 26,
    whiteSpace: "nowrap" as const,
  },
  interruptedDangerBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    padding: "3px 8px",
    borderRadius: 5,
    border: "1px solid rgba(248, 81, 73, 0.24)",
    color: "var(--danger)",
    background: "rgba(248, 81, 73, 0.055)",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    minHeight: 26,
    whiteSpace: "nowrap" as const,
  },
} satisfies Record<string, React.CSSProperties>;
