import type React from "react";

export const timeline = {
  timelinePane: {
    flex: 1,
    display: "flex",
    flexDirection: "column" as const,
    overflowY: "auto" as const,
    background: "var(--aegis-elevated)",
    padding: "28px 28px 32px",
  },
  timelineHeader: {
    fontSize: 14,
    fontWeight: 700,
    color: "rgb(var(--aegis-text))",
    marginBottom: 4,
  },
  timelineSubtitle: {
    fontSize: 12,
    color: "rgb(var(--aegis-text-muted))",
    marginBottom: 24,
  },
  timelineGroup: {
    display: "flex",
    flexDirection: "column" as const,
    marginBottom: 24,
  },
  timelineGroupHeader: {
    display: "flex",
    alignItems: "baseline" as const,
    gap: 10,
    marginBottom: 10,
    paddingBottom: 8,
    borderBottom: "1px solid var(--aegis-border)",
  },
  timelineGroupTitle: {
    fontSize: 12,
    fontWeight: 700,
    color: "rgb(var(--aegis-text-secondary))",
    letterSpacing: 0.4,
    textTransform: "uppercase" as const,
  },
  timelineGroupCount: {
    fontSize: 11.5,
    color: "rgb(var(--aegis-text-dim))",
    fontWeight: 500,
  },
  timelineProjectBlock: {
    display: "flex",
    flexDirection: "column" as const,
    marginBottom: 14,
  },
  timelineProjectHeader: {
    display: "flex",
    alignItems: "center" as const,
    gap: 8,
    padding: "6px 0",
    marginBottom: 4,
  },
  timelineProjectName: {
    fontSize: 13,
    fontWeight: 600,
    color: "rgb(var(--aegis-text))",
    overflow: "hidden" as const,
    textOverflow: "ellipsis" as const,
    whiteSpace: "nowrap" as const,
  },
  timelineProjectCount: {
    fontSize: 11,
    color: "rgb(var(--aegis-text-dim))",
    fontWeight: 500,
  },
  timelineList: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 2,
  },
  timelineRow: {
    display: "flex",
    alignItems: "center" as const,
    gap: 10,
    padding: "6px 8px",
    borderRadius: 6,
    cursor: "pointer",
    border: "none",
    background: "transparent",
    textAlign: "left" as const,
    width: "100%",
  },
  timelineRowTime: {
    fontSize: 11.5,
    color: "rgb(var(--aegis-text-dim))",
    fontVariantNumeric: "tabular-nums" as const,
    width: 48,
    flexShrink: 0,
  },
  timelineRowStatus: {
    flexShrink: 0,
    display: "flex",
    alignItems: "center" as const,
  },
  timelineRowMain: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column" as const,
    gap: 2,
  },
  timelineRowTitle: {
    fontSize: 13,
    color: "rgb(var(--aegis-text))",
    fontWeight: 500,
    overflow: "hidden" as const,
    textOverflow: "ellipsis" as const,
    whiteSpace: "nowrap" as const,
  },
  timelineRowMeta: {
    display: "flex",
    alignItems: "center" as const,
    gap: 8,
    fontSize: 11.5,
    color: "rgb(var(--aegis-text-muted))",
  },
  timelineRowMetaSep: {
    color: "rgb(var(--aegis-text-dim))",
  },
  timelineRowDiff: {
    fontVariantNumeric: "tabular-nums" as const,
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 11,
  },
  timelineRowDiffAdd: {
    color: "var(--git-added, #16a34a)",
  },
  timelineRowDiffDel: {
    color: "var(--git-removed, #dc2626)",
  },
  timelineEmpty: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    padding: "60px 24px",
    color: "rgb(var(--aegis-text-muted))",
    fontSize: 13,
    textAlign: "center" as const,
    gap: 12,
  },
} satisfies Record<string, React.CSSProperties>;
