import type { DingTalkToolSpec } from "./types.js";

export const RUNTIME_STATUS_TOOL_NAME = "junqi_dingtalk_runtime_status";
export const TOOL_SCHEMA_TOOL_NAME = "junqi_dingtalk_tool_schema";

export const DINGTALK_TOOL_SPECS = [
  { name: "junqi_dingtalk_contact_me", label: "当前用户", description: "读取当前钉钉用户资料", domain: "contact", canonicalPath: "contact.get_current_user_profile", cliPath: "contact user get-self", effect: "read", risk: "low", confirmation: "not_required", idempotency: "idempotent" },
  { name: "junqi_dingtalk_contact_search_users", label: "搜索成员", description: "按关键词搜索组织成员", domain: "contact", canonicalPath: "contact.search_contact_by_key_word", cliPath: "contact user search", effect: "read", risk: "low", confirmation: "not_required", idempotency: "idempotent" },
  { name: "junqi_dingtalk_contact_search_departments", label: "搜索部门", description: "按关键词搜索组织部门", domain: "contact", canonicalPath: "contact.search_dept_by_keyword", cliPath: "contact dept search", effect: "read", risk: "low", confirmation: "not_required", idempotency: "idempotent" },
  { name: "junqi_dingtalk_contact_department_members", label: "部门成员", description: "读取指定部门成员", domain: "contact", canonicalPath: "contact.get_dept_members_by_deptId", cliPath: "contact dept list-members", effect: "read", risk: "low", confirmation: "not_required", idempotency: "idempotent" },
  { name: "junqi_dingtalk_approval_forms", label: "审批表单", description: "列出当前用户可见审批表单", domain: "approval", canonicalPath: "oa.list_user_visible_process", cliPath: "oa approval list-forms", effect: "read", risk: "low", confirmation: "not_required", idempotency: "idempotent" },
  { name: "junqi_dingtalk_approval_pending", label: "待审批", description: "查询当前用户待处理审批", domain: "approval", canonicalPath: "oa.list_pending_approvals", cliPath: "oa approval list-pending", effect: "read", risk: "low", confirmation: "not_required", idempotency: "idempotent" },
  { name: "junqi_dingtalk_approval_submitted", label: "已提交审批", description: "查询当前用户提交的审批", domain: "approval", canonicalPath: "oa.get_submitted_instances", cliPath: "oa approval list-submitted", effect: "read", risk: "low", confirmation: "not_required", idempotency: "idempotent" },
  { name: "junqi_dingtalk_approval_detail", label: "审批详情", description: "读取审批实例详情", domain: "approval", canonicalPath: "oa.get_processInstance_detail", cliPath: "oa approval detail", effect: "read", risk: "low", confirmation: "not_required", idempotency: "idempotent" },
  { name: "junqi_dingtalk_approval_records", label: "审批记录", description: "读取审批实例的操作记录", domain: "approval", canonicalPath: "oa.get_processInstance_records", cliPath: "oa approval records", effect: "read", risk: "low", confirmation: "not_required", idempotency: "idempotent" },
  { name: "junqi_dingtalk_approval_tasks", label: "审批任务", description: "读取指定审批实例的待处理任务", domain: "approval", canonicalPath: "oa.list_pending_tasks", cliPath: "oa approval tasks", effect: "read", risk: "low", confirmation: "not_required", idempotency: "idempotent" },
  { name: "junqi_dingtalk_approval_form_schema", label: "审批字段", description: "读取审批表单字段定义", domain: "approval", canonicalPath: "oa.get_process_schema", cliPath: "oa approval form-schema", effect: "read", risk: "low", confirmation: "not_required", idempotency: "idempotent" },
  { name: "junqi_dingtalk_approval_forecast", label: "审批流程预测", description: "根据审批表单值读取 DWS 返回的流程预测", domain: "approval", canonicalPath: "oa.forecast_process", cliPath: "oa approval forecast-process", effect: "read", risk: "low", confirmation: "not_required", idempotency: "idempotent" },
  { name: "junqi_dingtalk_attendance_record", label: "考勤记录", description: "读取成员指定日期考勤记录", domain: "attendance", canonicalPath: "attendance.get_user_attendance_record", cliPath: "attendance record get", effect: "read", risk: "low", confirmation: "not_required", idempotency: "idempotent" },
  { name: "junqi_dingtalk_attendance_summary", label: "考勤汇总", description: "读取成员考勤汇总", domain: "attendance", canonicalPath: "attendance.get_attendance_summary", cliPath: "attendance summary", effect: "read", risk: "low", confirmation: "not_required", idempotency: "idempotent" },
  { name: "junqi_dingtalk_attendance_rules", label: "考勤规则", description: "读取指定日期考勤组和规则", domain: "attendance", canonicalPath: "attendance.query_attendance_group_or_rules", cliPath: "attendance rules", effect: "read", risk: "low", confirmation: "not_required", idempotency: "idempotent" },
  { name: "junqi_dingtalk_attendance_shifts", label: "成员排班", description: "批量读取成员日期范围排班", domain: "attendance", canonicalPath: "attendance.batch_get_employee_shifts", cliPath: "attendance shift list", effect: "read", risk: "low", confirmation: "not_required", idempotency: "idempotent" },
  { name: "junqi_dingtalk_calendar_events", label: "日程列表", description: "查询时间范围内日程", domain: "calendar", canonicalPath: "calendar.list_calendar_events", cliPath: "calendar event list", effect: "read", risk: "low", confirmation: "not_required", idempotency: "idempotent" },
  { name: "junqi_dingtalk_calendar_event", label: "日程详情", description: "读取指定日程详情", domain: "calendar", canonicalPath: "calendar.get_calendar_detail", cliPath: "calendar event get", effect: "read", risk: "low", confirmation: "not_required", idempotency: "idempotent" },
  { name: "junqi_dingtalk_calendar_busy", label: "忙闲查询", description: "查询成员或会议室忙闲状态", domain: "calendar", canonicalPath: "calendar.query_busy_status", cliPath: "calendar busy search", effect: "read", risk: "low", confirmation: "not_required", idempotency: "idempotent" },
  { name: "junqi_dingtalk_calendar_rooms", label: "可用会议室", description: "按时间和名称查询会议室", domain: "calendar", canonicalPath: "calendar.query_available_meeting_room", cliPath: "calendar room search", effect: "read", risk: "low", confirmation: "not_required", idempotency: "idempotent" },
  { name: "junqi_dingtalk_todo_tasks", label: "待办列表", description: "查询当前组织待办", domain: "todo", canonicalPath: "todo.get_user_todos_in_current_org", cliPath: "todo task list", effect: "read", risk: "low", confirmation: "not_required", idempotency: "idempotent" },
  { name: "junqi_dingtalk_todo_detail", label: "待办详情", description: "读取指定待办详情", domain: "todo", canonicalPath: "todo.get_todo_detail", cliPath: "todo task get", effect: "read", risk: "low", confirmation: "not_required", idempotency: "idempotent" },
  { name: "junqi_dingtalk_calendar_create", label: "创建日程", description: "创建钉钉日程", domain: "calendar", canonicalPath: "calendar.create_calendar_event", cliPath: "calendar event create", effect: "write", risk: "medium", confirmation: "not_required", idempotency: "unknown" },
  { name: "junqi_dingtalk_calendar_update", label: "更新日程", description: "更新钉钉日程", domain: "calendar", canonicalPath: "calendar.update_calendar_event", cliPath: "calendar event update", effect: "write", risk: "medium", confirmation: "not_required", idempotency: "unknown" },
  { name: "junqi_dingtalk_todo_create", label: "创建待办", description: "创建个人待办", domain: "todo", canonicalPath: "todo.create_personal_todo", cliPath: "todo task create", effect: "write", risk: "medium", confirmation: "not_required", idempotency: "unknown" },
  { name: "junqi_dingtalk_todo_update", label: "更新待办", description: "更新指定待办", domain: "todo", canonicalPath: "todo.update_todo_task", cliPath: "todo task update", effect: "write", risk: "medium", confirmation: "not_required", idempotency: "unknown" },
  { name: "junqi_dingtalk_todo_set_done", label: "更新待办状态", description: "设置指定待办完成状态", domain: "todo", canonicalPath: "todo.update_todo_done_status", cliPath: "todo task done", effect: "write", risk: "medium", confirmation: "not_required", idempotency: "unknown" },
  { name: "junqi_dingtalk_approval_create", label: "发起审批", description: "发起钉钉审批实例", domain: "approval", canonicalPath: "oa.start_process_instance", cliPath: "oa approval create-instance", effect: "write", risk: "high", confirmation: "user_required", idempotency: "non_idempotent" },
  { name: "junqi_dingtalk_approval_approve", label: "同意审批", description: "同意指定审批任务", domain: "approval", canonicalPath: "oa.approve_processInstance", cliPath: "oa approval approve", effect: "write", risk: "medium", confirmation: "not_required", idempotency: "unknown" },
  { name: "junqi_dingtalk_approval_reject", label: "拒绝审批", description: "拒绝指定审批任务", domain: "approval", canonicalPath: "oa.reject_processInstance", cliPath: "oa approval reject", effect: "write", risk: "medium", confirmation: "not_required", idempotency: "unknown" },
  { name: "junqi_dingtalk_approval_revoke", label: "撤销审批", description: "撤销指定审批实例", domain: "approval", canonicalPath: "oa.revoke_processInstance", cliPath: "oa approval revoke", effect: "write", risk: "high", confirmation: "user_required", idempotency: "unknown" },
] as const satisfies readonly DingTalkToolSpec[];

export const DINGTALK_TOOL_SPEC_BY_NAME: ReadonlyMap<string, DingTalkToolSpec> = new Map(
  DINGTALK_TOOL_SPECS.map((spec) => [spec.name, spec] as const),
);
