import assert from 'node:assert/strict';
import test from 'node:test';
import {
  cargoManifestVersion,
  checkReleaseVersionConsistency,
  collectReleaseVersions,
  describeVersionMismatch,
  lockfileCrateVersion,
} from './check-release-version-consistency.mjs';

const LOCKFILE = `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "base64"
version = "0.22.1"

[[package]]
name = "junqi-desktop"
version = "1.5.3"
dependencies = [
 "base64",
]

[[package]]
name = "serde"
version = "1.0.0"
`;

const CARGO_TOML = `[package]
name = "junqi-desktop"
version = "1.5.3"
edition = "2021"

[dependencies]
serde = "1.0.0"
`;

function sources({ pkg = '1.5.3', cargo = '1.5.3', tauri = '1.5.3', lock = '1.5.3' } = {}) {
  return {
    packageJson: JSON.stringify({ name: 'junqi-desktop', version: pkg }),
    cargoToml: CARGO_TOML.replace('version = "1.5.3"', `version = "${cargo}"`),
    tauriConf: JSON.stringify({ productName: 'JunQi', version: tauri }),
    cargoLock: LOCKFILE.replace('version = "1.5.3"', `version = "${lock}"`),
  };
}

test('the crate version is read from its own lockfile block', () => {
  assert.equal(lockfileCrateVersion(LOCKFILE), '1.5.3');
  // Neighbouring packages must not be mistaken for the desktop crate.
  assert.equal(lockfileCrateVersion(LOCKFILE, 'base64'), '0.22.1');
  assert.equal(lockfileCrateVersion(LOCKFILE, 'absent-crate'), null);
});

test('the manifest version comes from [package], not from a dependency', () => {
  assert.equal(cargoManifestVersion(CARGO_TOML), '1.5.3');
});

test('four agreeing sources report no mismatch', () => {
  assert.equal(describeVersionMismatch(collectReleaseVersions(sources())), null);
});

// The exact shape of the v1.5.0 and v1.5.1 releases: three files bumped, the
// lockfile left behind, and no build failure to reveal it.
test('a stale lockfile is reported even when the other three agree', () => {
  const failure = describeVersionMismatch(collectReleaseVersions(sources({ lock: '1.5.2' })));
  assert.ok(failure);
  assert.match(failure, /Cargo\.lock/);
  assert.match(failure, /1\.5\.2/);
  assert.match(failure, /1\.5\.3/);
});

test('any single disagreeing source fails the check', () => {
  for (const key of ['pkg', 'cargo', 'tauri', 'lock']) {
    const failure = describeVersionMismatch(collectReleaseVersions(sources({ [key]: '9.9.9' })));
    assert.ok(failure, `${key} drift was not reported`);
  }
});

test('an unreadable version is a failure, never a silent pass', () => {
  const missing = collectReleaseVersions({
    packageJson: JSON.stringify({ name: 'junqi-desktop' }),
    cargoToml: CARGO_TOML,
    tauriConf: JSON.stringify({ version: '1.5.3' }),
    cargoLock: LOCKFILE,
  });
  const failure = describeVersionMismatch(missing);
  assert.ok(failure);
  assert.match(failure, /package\.json/);
});

test('the repository itself is version-consistent', () => {
  assert.equal(checkReleaseVersionConsistency(), null);
});
