import type { OpenClawCommandReference } from './types';

const DOCS_BASE = 'https://docs.openclaw.ai/cli';

const gateway: readonly OpenClawCommandReference[] = [
  {
    id: 'gateway-install',
    category: 'gateway',
    command: 'openclaw gateway install',
    summaryKey: 'openclawCommands.items.gatewayInstall',
    docsUrl: `${DOCS_BASE}/gateway#manage-the-gateway-service`,
    impact: 'action',
    keywords: ['gateway', 'install', 'service', 'launchd', 'systemd', 'schtasks', '安装', '服务'],
  },
  {
    id: 'gateway-start',
    category: 'gateway',
    command: 'openclaw gateway start',
    summaryKey: 'openclawCommands.items.gatewayStart',
    docsUrl: `${DOCS_BASE}/gateway#manage-the-gateway-service`,
    impact: 'action',
    keywords: ['gateway', 'start', 'service', 'daemon', '启动', '服务'],
  },
  {
    id: 'gateway-stop',
    category: 'gateway',
    command: 'openclaw gateway stop',
    summaryKey: 'openclawCommands.items.gatewayStop',
    docsUrl: `${DOCS_BASE}/gateway#manage-the-gateway-service`,
    impact: 'action',
    keywords: ['gateway', 'stop', 'disable', 'service', '停止', '禁用'],
  },
  {
    id: 'gateway-safe-restart',
    category: 'gateway',
    command: 'openclaw gateway restart --safe',
    summaryKey: 'openclawCommands.items.gatewaySafeRestart',
    docsUrl: `${DOCS_BASE}/gateway#restart-the-gateway`,
    impact: 'action',
    keywords: ['gateway', 'restart', 'safe', 'drain', 'coalesce', '重启', '排空'],
  },
  {
    id: 'gateway-run-verbose',
    category: 'gateway',
    command: 'openclaw gateway run --verbose',
    summaryKey: 'openclawCommands.items.gatewayRunVerbose',
    docsUrl: `${DOCS_BASE}/gateway#run-the-gateway`,
    impact: 'action',
    keywords: ['gateway', 'run', 'foreground', 'verbose', 'startup', '前台', '启动诊断'],
  },
  {
    id: 'gateway-status',
    category: 'gateway',
    command: 'openclaw gateway status --require-rpc',
    summaryKey: 'openclawCommands.items.gatewayStatus',
    docsUrl: `${DOCS_BASE}/gateway#gateway-status`,
    impact: 'live',
    keywords: ['gateway', 'status', 'rpc', 'service', '状态', '连通性'],
  },
  {
    id: 'gateway-probe',
    category: 'gateway',
    command: 'openclaw gateway probe',
    summaryKey: 'openclawCommands.items.gatewayProbe',
    docsUrl: `${DOCS_BASE}/gateway#gateway-probe`,
    impact: 'live',
    keywords: ['gateway', 'probe', 'remote', 'loopback', 'auth', 'rpc', '探测', '认证'],
  },
  {
    id: 'gateway-stability',
    category: 'gateway',
    command: 'openclaw gateway stability --bundle latest',
    summaryKey: 'openclawCommands.items.gatewayStability',
    docsUrl: `${DOCS_BASE}/gateway#gateway-stability`,
    impact: 'read',
    keywords: ['gateway', 'stability', 'bundle', 'crash', 'startup', '稳定性', '崩溃'],
  },
  {
    id: 'gateway-diagnostics-export',
    category: 'gateway',
    command: 'openclaw gateway diagnostics export --output <path>',
    copyCommand: 'openclaw gateway diagnostics export --output "$OUTPUT_PATH"',
    summaryKey: 'openclawCommands.items.gatewayDiagnosticsExport',
    docsUrl: `${DOCS_BASE}/gateway#gateway-diagnostics-export`,
    impact: 'action',
    keywords: ['gateway', 'diagnostics', 'export', 'zip', 'redacted', 'support', '诊断包', '脱敏'],
  },
];

const diagnostics: readonly OpenClawCommandReference[] = [
  {
    id: 'status-all',
    category: 'diagnostics',
    command: 'openclaw status --all',
    summaryKey: 'openclawCommands.items.statusAll',
    docsUrl: `${DOCS_BASE}/status`,
    impact: 'read',
    keywords: ['status', 'all', 'security audit', 'plugins', 'memory', 'diagnostics', '状态', '诊断'],
  },
  {
    id: 'status-deep',
    category: 'diagnostics',
    command: 'openclaw status --deep',
    summaryKey: 'openclawCommands.items.statusDeep',
    docsUrl: `${DOCS_BASE}/status`,
    impact: 'live',
    keywords: ['status', 'deep', 'channels', 'probe', 'security audit', '渠道', '实时探测'],
  },
  {
    id: 'health-verbose',
    category: 'diagnostics',
    command: 'openclaw health --verbose',
    summaryKey: 'openclawCommands.items.healthVerbose',
    docsUrl: `${DOCS_BASE}/health#openclaw-health`,
    impact: 'live',
    keywords: ['health', 'verbose', 'websocket', 'rpc', 'accounts', 'agents', '健康', '探测'],
  },
  {
    id: 'logs-follow',
    category: 'diagnostics',
    command: 'openclaw logs --follow --local-time',
    summaryKey: 'openclawCommands.items.logsFollow',
    docsUrl: `${DOCS_BASE}/logs#examples`,
    impact: 'live',
    keywords: ['logs', 'follow', 'tail', 'local time', 'rpc', 'reconnect', '日志', '跟踪'],
  },
  {
    id: 'doctor-lint',
    category: 'diagnostics',
    command: 'openclaw doctor --lint --json',
    summaryKey: 'openclawCommands.items.doctorLint',
    docsUrl: `${DOCS_BASE}/doctor#lint-mode`,
    impact: 'read',
    keywords: ['doctor', 'lint', 'json', 'ci', 'diagnostics', '诊断', '只读'],
  },
  {
    id: 'doctor-fix',
    category: 'diagnostics',
    command: 'openclaw doctor --fix',
    summaryKey: 'openclawCommands.items.doctorFix',
    docsUrl: `${DOCS_BASE}/doctor#postures`,
    impact: 'action',
    keywords: ['doctor', 'fix', 'repair', 'migration', 'plugins', 'skills', '修复', '迁移'],
  },
  {
    id: 'security-audit-deep',
    category: 'diagnostics',
    command: 'openclaw security audit --deep --json',
    summaryKey: 'openclawCommands.items.securityAuditDeep',
    docsUrl: `${DOCS_BASE}/security#audit-modes`,
    impact: 'live',
    keywords: ['security', 'audit', 'deep', 'json', 'gateway', 'plugins', '安全', '审计'],
  },
  {
    id: 'secrets-audit',
    category: 'diagnostics',
    command: 'openclaw secrets audit --check',
    summaryKey: 'openclawCommands.items.secretsAudit',
    docsUrl: `${DOCS_BASE}/secrets#audit`,
    impact: 'read',
    keywords: ['secrets', 'audit', 'check', 'secretref', 'plaintext', 'drift', '密钥', '审计'],
  },
  {
    id: 'secrets-reload',
    category: 'diagnostics',
    command: 'openclaw secrets reload',
    summaryKey: 'openclawCommands.items.secretsReload',
    docsUrl: `${DOCS_BASE}/secrets#reload-runtime-snapshot`,
    impact: 'action',
    keywords: ['secrets', 'reload', 'secretref', 'runtime', 'snapshot', 'atomic', '密钥', '热重载'],
  },
];

export const GATEWAY_COMMANDS = { gateway, diagnostics } as const;
