import type { OpenClawCommandReference } from './types';

const DOCS_URL = 'https://docs.openclaw.ai/cli/models';

const models: readonly OpenClawCommandReference[] = [
  {
    id: 'models-status',
    category: 'models',
    command: 'openclaw models status',
    summaryKey: 'openclawCommands.items.modelsStatus',
    docsUrl: `${DOCS_URL}#status`,
    impact: 'read',
    keywords: ['models', 'status', 'default', 'fallbacks', 'auth', 'quota', '模型', '认证', '配额'],
  },
  {
    id: 'models-status-check',
    category: 'models',
    command: 'openclaw models status --check',
    summaryKey: 'openclawCommands.items.modelsStatusCheck',
    docsUrl: `${DOCS_URL}#status`,
    impact: 'read',
    keywords: ['models', 'status', 'check', 'exit code', 'expired', 'ci', '认证', '健康门禁'],
  },
  {
    id: 'models-status-probe',
    category: 'models',
    command: 'openclaw models status --probe --probe-provider <name>',
    copyCommand: 'openclaw models status --probe --probe-provider "$PROVIDER"',
    summaryKey: 'openclawCommands.items.modelsStatusProbe',
    docsUrl: `${DOCS_URL}#status`,
    impact: 'live',
    keywords: ['models', 'status', 'probe', 'provider', 'token', 'billing', 'rate limit', '真实请求', '计费'],
  },
  {
    id: 'models-list-provider',
    category: 'models',
    command: 'openclaw models list --all --provider <id>',
    copyCommand: 'openclaw models list --all --provider "$PROVIDER"',
    summaryKey: 'openclawCommands.items.modelsListProvider',
    docsUrl: `${DOCS_URL}#list`,
    impact: 'read',
    keywords: ['models', 'list', 'all', 'provider', 'catalog', 'availability', '模型', '提供商'],
  },
  {
    id: 'models-list-local',
    category: 'models',
    command: 'openclaw models list --local',
    summaryKey: 'openclawCommands.items.modelsListLocal',
    docsUrl: `${DOCS_URL}#list`,
    impact: 'read',
    keywords: ['models', 'list', 'local', 'catalog', '本地模型', '目录'],
  },
  {
    id: 'models-set',
    category: 'models',
    command: 'openclaw models set <model-or-alias>',
    copyCommand: 'openclaw models set "$MODEL"',
    summaryKey: 'openclawCommands.items.modelsSet',
    docsUrl: `${DOCS_URL}#set-default-%252F-image-model`,
    impact: 'action',
    keywords: ['models', 'set', 'default', 'primary', 'alias', 'codex', 'copilot', '默认模型', '别名'],
  },
  {
    id: 'models-set-image',
    category: 'models',
    command: 'openclaw models set-image <model-or-alias>',
    copyCommand: 'openclaw models set-image "$IMAGE_MODEL"',
    summaryKey: 'openclawCommands.items.modelsSetImage',
    docsUrl: `${DOCS_URL}#set-default-%252F-image-model`,
    impact: 'action',
    keywords: ['models', 'set-image', 'image model', 'default', 'primary', '图像模型', '默认模型'],
  },
  {
    id: 'models-aliases-list',
    category: 'models',
    command: 'openclaw models aliases list --json',
    summaryKey: 'openclawCommands.items.modelsAliasesList',
    docsUrl: `${DOCS_URL}#aliases`,
    impact: 'read',
    keywords: ['models', 'aliases', 'list', 'json', 'canonical', '模型别名', '映射'],
  },
  {
    id: 'models-aliases-add',
    category: 'models',
    command: 'openclaw models aliases add <alias> <model-or-alias>',
    copyCommand: 'openclaw models aliases add "$ALIAS" "$MODEL"',
    summaryKey: 'openclawCommands.items.modelsAliasesAdd',
    docsUrl: `${DOCS_URL}#aliases`,
    impact: 'action',
    keywords: ['models', 'aliases', 'add', 'update', 'canonical', '别名', '添加'],
  },
  {
    id: 'models-aliases-remove',
    category: 'models',
    command: 'openclaw models aliases remove <alias>',
    copyCommand: 'openclaw models aliases remove "$ALIAS"',
    summaryKey: 'openclawCommands.items.modelsAliasesRemove',
    docsUrl: `${DOCS_URL}#aliases`,
    impact: 'action',
    keywords: ['models', 'aliases', 'remove', 'builtin', '删除别名', '内置别名'],
  },
  {
    id: 'models-fallbacks-list',
    category: 'models',
    command: 'openclaw models fallbacks list --json',
    summaryKey: 'openclawCommands.items.modelsFallbacksList',
    docsUrl: `${DOCS_URL}#fallbacks`,
    impact: 'read',
    keywords: ['models', 'fallbacks', 'list', 'json', 'order', '回退模型', '顺序'],
  },
  {
    id: 'models-fallbacks-add',
    category: 'models',
    command: 'openclaw models fallbacks add <model-or-alias>',
    copyCommand: 'openclaw models fallbacks add "$MODEL"',
    summaryKey: 'openclawCommands.items.modelsFallbacksAdd',
    docsUrl: `${DOCS_URL}#fallbacks`,
    impact: 'action',
    keywords: ['models', 'fallbacks', 'add', 'remove', 'clear', '文本模型', '回退'],
  },
  {
    id: 'models-image-fallbacks-add',
    category: 'models',
    command: 'openclaw models image-fallbacks add <model-or-alias>',
    copyCommand: 'openclaw models image-fallbacks add "$IMAGE_MODEL"',
    summaryKey: 'openclawCommands.items.modelsImageFallbacksAdd',
    docsUrl: `${DOCS_URL}#fallbacks`,
    impact: 'action',
    keywords: ['models', 'image-fallbacks', 'add', 'remove', 'clear', '图像模型', '回退'],
  },
];

const auth: readonly OpenClawCommandReference[] = [
  {
    id: 'models-auth-list',
    category: 'auth',
    command: 'openclaw models auth list --provider <id> --json',
    copyCommand: 'openclaw models auth list --provider "$PROVIDER" --json',
    summaryKey: 'openclawCommands.items.modelsAuthList',
    docsUrl: `${DOCS_URL}#auth-profiles`,
    impact: 'read',
    keywords: ['models', 'auth', 'list', 'provider', 'profiles', 'secrets', '认证档案', '密钥保护'],
  },
  {
    id: 'models-auth-add',
    category: 'auth',
    command: 'openclaw models auth add',
    summaryKey: 'openclawCommands.items.modelsAuthAdd',
    docsUrl: `${DOCS_URL}#auth-profiles`,
    impact: 'action',
    keywords: ['models', 'auth', 'add', 'interactive', 'oauth', 'api key', 'token', '添加认证'],
  },
  {
    id: 'models-auth-login',
    category: 'auth',
    command: 'openclaw models auth login --provider <id> --set-default',
    copyCommand: 'openclaw models auth login --provider "$PROVIDER" --set-default',
    summaryKey: 'openclawCommands.items.modelsAuthLogin',
    docsUrl: `${DOCS_URL}#auth-profiles`,
    impact: 'action',
    keywords: ['models', 'auth', 'login', 'provider', 'openai', 'chatgpt', 'codex', 'api-key', '登录', '认证'],
  },
  {
    id: 'models-auth-paste-api-key',
    category: 'auth',
    command: 'openclaw models auth paste-api-key --provider <id>',
    copyCommand: 'openclaw models auth paste-api-key --provider "$PROVIDER"',
    summaryKey: 'openclawCommands.items.modelsAuthPasteApiKey',
    docsUrl: `${DOCS_URL}#auth-profiles`,
    impact: 'action',
    keywords: ['models', 'auth', 'paste-api-key', 'stdin', 'shell history', 'manual', 'API Key', '密钥'],
  },
  {
    id: 'models-auth-order-get',
    category: 'auth',
    command: 'openclaw models auth order get --provider <id> --json',
    copyCommand: 'openclaw models auth order get --provider "$PROVIDER" --json',
    summaryKey: 'openclawCommands.items.modelsAuthOrderGet',
    docsUrl: `${DOCS_URL}#auth-profiles`,
    impact: 'read',
    keywords: ['models', 'auth', 'order', 'get', 'provider', 'agent', 'auth-state', '认证顺序'],
  },
  {
    id: 'models-auth-order-set',
    category: 'auth',
    command: 'openclaw models auth order set --provider <id> <profileIds...>',
    copyCommand: 'openclaw models auth order set --provider "$PROVIDER" "$PROFILE_ID"',
    summaryKey: 'openclawCommands.items.modelsAuthOrderSet',
    docsUrl: `${DOCS_URL}#auth-profiles`,
    impact: 'action',
    keywords: ['models', 'auth', 'order', 'set', 'profile id', 'excluded', 'priority', '认证优先级'],
  },
  {
    id: 'models-auth-order-clear',
    category: 'auth',
    command: 'openclaw models auth order clear --provider <id>',
    copyCommand: 'openclaw models auth order clear --provider "$PROVIDER"',
    summaryKey: 'openclawCommands.items.modelsAuthOrderClear',
    docsUrl: `${DOCS_URL}#auth-profiles`,
    impact: 'action',
    keywords: ['models', 'auth', 'order', 'clear', 'round robin', 'override', '清除认证顺序'],
  },
];

export const MODEL_COMMANDS = { models, auth } as const;
