import type { OpenClawCommandReference } from './types';

const DOCS_BASE = 'https://docs.openclaw.ai/cli';

const setup: readonly OpenClawCommandReference[] = [
  {
    id: 'setup',
    category: 'setup',
    command: 'openclaw setup',
    summaryKey: 'openclawCommands.items.setup',
    docsUrl: `${DOCS_BASE}/setup#openclaw-setup`,
    impact: 'action',
    keywords: ['setup', 'baseline', 'onboarding', 'workspace', 'gateway', '初始化', '配置'],
  },
  {
    id: 'config-get',
    category: 'setup',
    command: 'openclaw config get <path> --json',
    copyCommand: 'openclaw config get "$CONFIG_PATH" --json',
    summaryKey: 'openclawCommands.items.configGet',
    docsUrl: `${DOCS_BASE}/config#config-get`,
    impact: 'read',
    keywords: ['config', 'get', 'json', 'path', '读取', '配置'],
  },
  {
    id: 'config-set',
    category: 'setup',
    command: 'openclaw config set <path> <value> --dry-run',
    copyCommand: 'openclaw config set "$CONFIG_PATH" "$CONFIG_VALUE" --dry-run',
    summaryKey: 'openclawCommands.items.configSet',
    docsUrl: `${DOCS_BASE}/config#config-set-modes`,
    impact: 'mixed',
    keywords: ['config', 'set', 'strict json', 'dry run', '写入', '配置'],
  },
  {
    id: 'config-validate',
    category: 'setup',
    command: 'openclaw config validate',
    summaryKey: 'openclawCommands.items.configValidate',
    docsUrl: `${DOCS_BASE}/config#config-validate`,
    impact: 'read',
    keywords: ['config', 'validate', 'schema', 'json', '校验', '配置'],
  },
  {
    id: 'update-status',
    category: 'setup',
    command: 'openclaw update status',
    summaryKey: 'openclawCommands.items.updateStatus',
    docsUrl: `${DOCS_BASE}/update#update-status`,
    impact: 'live',
    keywords: ['update', 'status', 'version', 'channel', '升级', '版本'],
  },
];

const channels: readonly OpenClawCommandReference[] = [
  {
    id: 'channels-list',
    category: 'channels',
    command: 'openclaw channels list --all',
    summaryKey: 'openclawCommands.items.channelsList',
    docsUrl: `${DOCS_BASE}/channels#common-commands`,
    impact: 'read',
    keywords: ['channels', 'list', 'accounts', 'installed', 'configured', '渠道', '账号'],
  },
  {
    id: 'channels-probe',
    category: 'channels',
    command: 'openclaw channels status --probe',
    summaryKey: 'openclawCommands.items.channelsProbe',
    docsUrl: `${DOCS_BASE}/channels#status-%252F-capabilities-%252F-resolve-%252F-logs`,
    impact: 'live',
    keywords: ['channels', 'status', 'probe', 'audit', '渠道', '探测'],
  },
  {
    id: 'channels-add',
    category: 'channels',
    command: 'openclaw channels add',
    summaryKey: 'openclawCommands.items.channelsAdd',
    docsUrl: `${DOCS_BASE}/channels#add-%252F-remove-accounts`,
    impact: 'action',
    keywords: ['channels', 'add', 'account', 'wizard', '渠道', '添加', '账号'],
  },
  {
    id: 'channels-login',
    category: 'channels',
    command: 'openclaw channels login --channel <id>',
    copyCommand: 'openclaw channels login --channel "$CHANNEL"',
    summaryKey: 'openclawCommands.items.channelsLogin',
    docsUrl: `${DOCS_BASE}/channels#login-and-logout-(interactive)`,
    impact: 'action',
    keywords: ['channels', 'login', 'interactive', 'account', '渠道', '登录'],
  },
  {
    id: 'agents-list',
    category: 'channels',
    command: 'openclaw agents list --bindings',
    summaryKey: 'openclawCommands.items.agentsList',
    docsUrl: `${DOCS_BASE}/agents#agents-list`,
    impact: 'read',
    keywords: ['agents', 'list', 'bindings', 'routing', '智能体', '路由'],
  },
];

const automation: readonly OpenClawCommandReference[] = [
  {
    id: 'sessions',
    category: 'automation',
    command: 'openclaw sessions --active 120 --limit 25',
    summaryKey: 'openclawCommands.items.sessions',
    docsUrl: `${DOCS_BASE}/sessions#openclaw-sessions`,
    impact: 'read',
    keywords: ['sessions', 'active', 'limit', 'conversation', '会话', '最近活动'],
  },
  {
    id: 'message-send',
    category: 'automation',
    command: 'openclaw message send --channel <name> --target <dest> --message <text>',
    copyCommand: 'openclaw message send --channel "$CHANNEL" --target "$TARGET" --message "$MESSAGE"',
    summaryKey: 'openclawCommands.items.messageSend',
    docsUrl: `${DOCS_BASE}/message#send`,
    impact: 'action',
    keywords: ['message', 'send', 'channel', 'target', '消息', '发送'],
  },
  {
    id: 'cron-list',
    category: 'automation',
    command: 'openclaw cron list',
    summaryKey: 'openclawCommands.items.cronList',
    docsUrl: `${DOCS_BASE}/cron#common-admin-commands`,
    impact: 'live',
    keywords: ['cron', 'status', 'list', 'jobs', '定时任务', '列表'],
  },
  {
    id: 'cron-create',
    category: 'automation',
    command: 'openclaw cron create <schedule> <prompt>',
    copyCommand: 'openclaw cron create "$SCHEDULE" "$PROMPT"',
    summaryKey: 'openclawCommands.items.cronCreate',
    docsUrl: `${DOCS_BASE}/cron#create-jobs-quickly`,
    impact: 'action',
    keywords: ['cron', 'create', 'schedule', 'prompt', '定时任务', '创建'],
  },
  {
    id: 'cron-run',
    category: 'automation',
    command: 'openclaw cron run <job-id> --wait',
    copyCommand: 'openclaw cron run "$JOB_ID" --wait',
    summaryKey: 'openclawCommands.items.cronRun',
    docsUrl: `${DOCS_BASE}/cron#manual-runs`,
    impact: 'action',
    keywords: ['cron', 'run', 'job', 'wait', '定时任务', '运行'],
  },
  {
    id: 'skills-list',
    category: 'automation',
    command: 'openclaw skills list',
    summaryKey: 'openclawCommands.items.skillsList',
    docsUrl: `${DOCS_BASE}/skills#commands`,
    impact: 'read',
    keywords: ['skills', 'list', 'check', 'eligible', '技能', '检查'],
  },
  {
    id: 'skills-check',
    category: 'automation',
    command: 'openclaw skills check',
    summaryKey: 'openclawCommands.items.skillsCheck',
    docsUrl: `${DOCS_BASE}/skills#commands`,
    impact: 'read',
    keywords: ['skills', 'check', 'dependencies', 'environment', '技能', '依赖', '检查'],
  },
];

export const CORE_COMMANDS = { setup, channels, automation } as const;
